[package]
name = "aphrodite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo = "0.0.4"
image = "0.24.6"
smithay = {version = "0.3.0", features=["backend_winit", "renderer_gl", "wayland_frontend"]}
smithay-client-toolkit = "0.17.0"
